export const dummydata = [
    {
        title: "Design Homepage",
        description: "Create a responsive homepage layout",
        status: "PENDING",
        due_date: "2025-08-25",
        id: "task-001",
    },
    {
        title: "Write API Docs",
        description: "Document all endpoints for user service",
        status: "IN_PROGRESS",
        due_date: "2025-08-27",
        id: "task-002",
    },
    {
        title: "Fix Login Bug",
        description: "Resolve issue with Google sign-in flow",
        status: "COMPLETED",
        due_date: "2025-07-20",
        id: "task-003",
    },
    {
        title: "Add Unit Tests",
        description: "Cover 80% test cases for utils",
        status: "PENDING",
        due_date: "2025-07-28",
        id: "task-004",
    },
    {
        title: "Team Sync",
        description: "Schedule weekly team sync-up call",
        status: "PENDING",
        due_date: "2025-07-29",
        id: "task-005",
    },
    {
        title: "Deploy Staging",
        description: "Deploy latest changes to staging environment",
        status: "IN_PROGRESS",
        due_date: "2025-07-26",
        id: "task-006",
    },
    {
        title: "Update UI Library",
        description: "Upgrade to latest version of component library",
        status: "COMPLETED",
        due_date: "2025-07-22",
        id: "task-007",
    },
    {
        title: "Optimize Images",
        description: "Compress images for faster loading",
        status: "OVERDUE",
        due_date: "2025-07-30",
        id: "task-008",
    },
    {
        title: "Refactor Sidebar",
        description: "Clean up sidebar component structure",
        status: "OVERDUE",
        due_date: "2025-07-27",
        id: "task-009",
    },
    {
        title: "Client Feedback",
        description: "Incorporate client feedback into dashboard",
        status: "PENDING",
        due_date: "2025-07-31",
        id: "task-010",
    },
    {
        title: "Push Notification",
        description: "Implement push notification for alerts",
        status: "IN_PROGRESS",
        due_date: "2025-07-28",
        id: "task-011",
    },
    {
        title: "Onboarding Flow",
        description: "Design onboarding screens for new users",
        status: "OVERDUE",
        due_date: "2025-07-23",
        id: "task-012",
    },
    {
        title: "Fix Typos",
        description: "Correct text in FAQs and help section",
        status: "COMPLETED",
        due_date: "2025-07-21",
        id: "task-013",
    },
    {
        title: "Create Figma File",
        description: "Design high-fidelity mockups in Figma",
        status: "PENDING",
        due_date: "2025-07-30",
        id: "task-014",
    },
];
